DOMAIN = "smartalarm"
BASE_URL = "https://mijn.smartalarm.nl"
DEFAULT_SCAN_INTERVAL = 5
DEVICE_SCAN_INTERVAL = 30
BASE_ID = "1429"

STATE_AWAY = "away"
STATE_HOME = "home"
STATE_DISARM = "disarm"

STATE_NAMES = {
    STATE_AWAY: "Alarm aan",
    STATE_HOME: "Alarm thuis aan",
    STATE_DISARM: "Alarm uit",
}

SIGNAL_CALIBRATION_SAMPLES = 10
SIGNAL_NORMAL_RATIO = 0.90
SIGNAL_WARNING_RATIO = 0.75
SIGNAL_STALE_AFTER_MINUTES = 10
